train:
  model_name: ResNet50
  activation_func: sparse_categorical_crossentropy
  classes: 10
  save_path:  mlruns
  batch_size: 200
  epochs: 10
  dataset_name: cifar10
  image_size: [224, 224, 3] 
  target: None
  device: cpu
  skip: False
  
