train:
  model_name: VGG16
  activation_func: softmax
  loss_func: sparse_categorical_crossentropy
  classes: 10
  save_path:  mlruns
  batch_size: 200
  epochs: 10
  dataset_name: cifar10
  image_size: [224, 224, 3] 
  device: cpu
  skip: False

  
